# Generated by Django 6.1.1 on 2026-10-03 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(help_text='Unique station identifier from OPIS.', unique=True)),
                ('name', models.CharField(help_text='Name of the fuel station.', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Street address or nearby intersection.', max_length=255)),
                ('city', models.CharField(help_text='City where the station is located.', max_length=100)),
                ('state', models.CharField(help_text='Two-letter state abbreviation.', max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, help_text='OPIS fuel rack identifier, when available.', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees, when available.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees, when available.', max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Trip starting location.', max_length=255)),
                ('destination', models.CharField(help_text='Trip ending location.', max_length=255)),
                ('origin_latitude', models.DecimalField(decimal_places=6, help_text='Origin latitude in decimal degrees.', max_digits=9)),
                ('origin_longitude', models.DecimalField(decimal_places=6, help_text='Origin longitude in decimal degrees.', max_digits=9)),
                ('destination_latitude', models.DecimalField(decimal_places=6, help_text='Destination latitude in decimal degrees.', max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, help_text='Destination longitude in decimal degrees.', max_digits=9)),
                ('max_range_miles', models.PositiveSmallIntegerField(default=500, help_text='Maximum travel distance on a full tank, in miles.')),
                ('mpg', models.DecimalField(decimal_places=2, default=10, help_text='Vehicle fuel efficiency in miles per gallon.', max_digits=5)),
                ('initial_fuel_gallons', models.DecimalField(decimal_places=2, default=50, help_text='Fuel in the tank at the start of the trip, in gallons.', max_digits=6)),
                ('route_distance_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated route distance in miles.', max_digits=9, null=True)),
                ('route_geometry', models.JSONField(blank=True, help_text='Calculated route geometry as GeoJSON.', null=True)),
                ('estimated_fuel_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total fuel cost in dollars.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this trip was created.')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gallon', models.DecimalField(decimal_places=4, help_text='Retail price in dollars per gallon.', max_digits=7)),
                ('station', models.ForeignKey(help_text='Station this price belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='routes.fuelstation')),
            ],
        ),
        migrations.CreateModel(
            name='TripFuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='Order of this stop along the trip, starting at 1.')),
                ('distance_from_start_miles', models.DecimalField(decimal_places=2, help_text='Distance from the trip origin to this stop, in miles.', max_digits=9)),
                ('gallons_to_buy', models.DecimalField(decimal_places=3, help_text='Gallons to purchase at this stop.', max_digits=7)),
                ('price_per_gallon', models.DecimalField(decimal_places=4, help_text='Fuel price at this stop in dollars per gallon.', max_digits=7)),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated purchase cost at this stop in dollars.', max_digits=10)),
                ('station', models.ForeignKey(help_text='Station selected for this stop.', on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='routes.fuelstation')),
                ('trip', models.ForeignKey(help_text='Trip this fuel stop belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='routes.trip')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trip_fuel_stop_sequence')],
            },
        ),
    ]
